# PostgreSQL connection (values from environment, the .env file)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Schema managed via Flyway only (no Hibernate auto-DDL)
# Hibernate verifies that the existing database schema matches  Java entity mappings during  startup
spring.jpa.hibernate.ddl-auto=validate

# Let GlobalExceptionHandler handle 404s as JSON
spring.mvc.throw-exception-if-no-handler-found=true

# Required to prevent default welcome page from masking 404s
spring.web.resources.add-mappings=false

# Limits max pagination size to 100 for preventing DoS attacks.
spring.data.web.pageable.max-page-size=100

# Disable Spring Boot's built-in SQL initialization
spring.sql.init.mode=never

# Set to true despite auto-config, for explicit certainty
spring.flyway.enabled=true

# Set flyway location to classpath for explicit certainty
spring.flyway.locations=classpath:db/migration
